// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// The one implementation of what a mirrored file looks like here.
//
// mirror.js applies this on the way in. forward-port.js replays it to work out
// what the mirror produced, so it can tell an author's edit apart from the
// transform's own output and send only the edit upstream. Two copies of this
// logic would mean the forward-port silently attributing transform differences
// to the author, so there is exactly one.

const path = require("path");

const generatedNote = (source) =>
  `<!-- Mirrored from ${source.repo}/${source.sourcePath} at ${source.ref}. ` +
  `Do not edit this file here: edits are forwarded to ${source.repo}. -->\n`;

/**
 * Where a source file lands here, honouring fileMap. Returns null when a
 * fileMap is present and does not list the file, because then it is an
 * allowlist and the file is not mirrored at all.
 */
function targetRelPath(source, relPath) {
  const base = path.basename(relPath);
  if (!source.fileMap) return relPath;
  const mapped = source.fileMap[base];
  return mapped ? path.join(path.dirname(relPath), mapped) : null;
}

/**
 * Rewrite relative links between mirrored files to the paths they get here.
 *
 * Upstream pages link to each other by source filename. Those filenames change
 * when fileMap renames them, and the directory changes when they land here, so
 * every form has to be covered: with and without `./`, with and without the
 * extension. Missing one produces a link that resolves upstream and 404s here.
 *
 * Note this is deliberately lossy — four input forms collapse to one output —
 * which is why the forward-port replays it forward rather than trying to invert
 * it.
 */
function rewriteLinks(content, source, names) {
  let out = content;
  for (const name of names) {
    const mapped = source.fileMap ? source.fileMap[name] : null;
    const slug = (mapped || name).replace(/\.mdx?$/, "");
    const target = `${source.linkPrefix}/${slug}`;
    const bare = name.replace(/\.mdx?$/, "");
    for (const form of [`./${name}`, name, `./${bare}`, bare]) {
      out = out.split(`](${form})`).join(`](${target})`);
      out = out.split(`](${form}#`).join(`](${target}#`);
    }
  }
  return out;
}

/**
 * Put the generated note after the frontmatter, never before it. YAML
 * frontmatter has to be the first thing in the file; a comment above it is
 * parsed as body and the page loses its title, sidebar position and every
 * other field.
 */
function withGeneratedNote(body, note) {
  const fm = /^(---\r?\n[\s\S]*?\r?\n---\r?\n)/.exec(body);
  if (!fm) return note + body;
  return fm[1] + note + body.slice(fm[1].length);
}

/** Strip the note this module added, so a round trip can be checked. */
function withoutGeneratedNote(body, note) {
  return body.includes(note) ? body.replace(note, "") : body;
}

/**
 * Everything the mirror does to one file's bytes. `names` is every basename in
 * the source directory, which rewriteLinks needs to know what a link can point
 * at.
 */
function applyTransforms(body, source, names, outRel) {
  let out = body;
  if (source.transforms.includes("links")) out = rewriteLinks(out, source, names);
  if (/\.mdx?$/.test(outRel)) out = withGeneratedNote(out, generatedNote(source));
  return out;
}

module.exports = {
  generatedNote,
  targetRelPath,
  rewriteLinks,
  withGeneratedNote,
  withoutGeneratedNote,
  applyTransforms,
};
