#!/usr/bin/env node
// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Places fetched sources into content/ and records what came from where.
//
//   node scripts/mirror.js [name ...] [--check]
//
// --check writes nothing and exits non-zero if the tree would change. The
// mirror workflow uses it to decide whether there is anything to commit.
//
// The target directory is cleaned before writing, except for `preserve`
// entries, so a file deleted upstream disappears here too. That is the whole
// reason deletions propagate without anybody tracking them.

const fs = require("fs");
const path = require("path");

const { load, readLock, writeLock, REPO_ROOT } = require("./lib/sources");
const { CACHE } = require("./fetch-sources");

const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const only = new Set(args.filter((a) => !a.startsWith("--")));

const GENERATED_NOTE = (source) =>
  `<!-- Mirrored from ${source.repo}/${source.sourcePath} at ${source.ref}. ` +
  `Do not edit this file here: edits are forwarded to ${source.repo}. -->\n`;

/**
 * Rewrite relative links between mirrored files to the paths they get here.
 *
 * Upstream pages link to each other by source filename. Those filenames change
 * when fileMap renames them, and the directory changes when they land here, so
 * every form has to be covered: with and without `./`, with and without the
 * extension. Missing one produces a link that resolves upstream and 404s here,
 * which is how 18 of them got through the first time.
 */
function rewriteLinks(content, source, names) {
  let out = content;
  for (const name of names) {
    const mapped = source.fileMap ? source.fileMap[name] : null;
    const slug = (mapped || name).replace(/\.mdx?$/, "");
    const target = `${source.linkPrefix}/${slug}`;
    const bare = name.replace(/\.mdx?$/, "");
    for (const form of [`./${name}`, name, `./${bare}`, bare]) {
      out = out.split(`](${form})`).join(`](${target})`);
      out = out.split(`](${form}#`).join(`](${target}#`);
    }
  }
  return out;
}

/**
 * Put the generated note after the frontmatter, never before it. YAML
 * frontmatter has to be the first thing in the file; a comment above it is
 * parsed as body and the page loses its title, sidebar position and every
 * other field.
 */
function withGeneratedNote(body, note) {
  const fm = /^(---\r?\n[\s\S]*?\r?\n---\r?\n)/.exec(body);
  if (!fm) return note + body;
  return fm[1] + note + body.slice(fm[1].length);
}

function listFiles(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, base));
    else out.push(path.relative(base, full));
  }
  return out;
}

function mirrorOne(source, head) {
  const from = path.join(CACHE, source.name, source.sourcePath);
  const to = path.join(REPO_ROOT, source.targetPath);

  if (!fs.existsSync(from)) {
    throw new Error(`${source.name}: nothing fetched. Run scripts/fetch-sources.js first.`);
  }

  const incoming = listFiles(from).filter((f) => !source.exclude.has(path.basename(f)));
  const names = incoming.map((f) => path.basename(f));
  const planned = new Map();

  for (const rel of incoming) {
    const base = path.basename(rel);
    const mapped = source.fileMap ? source.fileMap[base] : null;
    if (source.fileMap && !mapped) continue; // fileMap is an allowlist when present
    const outRel = mapped ? path.join(path.dirname(rel), mapped) : rel;

    let body = fs.readFileSync(path.join(from, rel), "utf8");
    if (source.transforms.includes("links")) body = rewriteLinks(body, source, names);
    if (/\.mdx?$/.test(outRel)) body = withGeneratedNote(body, GENERATED_NOTE(source));

    planned.set(outRel, body);
  }

  // What is here now, minus the files this repo authors.
  const existing = listFiles(to).filter((f) => !source.preserve.has(f));

  let changed = 0;
  const removals = existing.filter((f) => !planned.has(f));
  for (const [rel, body] of planned) {
    const full = path.join(to, rel);
    const before = fs.existsSync(full) ? fs.readFileSync(full, "utf8") : null;
    if (before === body) continue;
    changed++;
    if (!checkOnly) {
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, body);
    }
  }
  if (!checkOnly) {
    for (const rel of removals) fs.rmSync(path.join(to, rel), { force: true });
  }

  console.log(
    `  ${source.name}: ${planned.size} file(s), ${changed} changed, ${removals.length} removed` +
      (source.preserve.size ? `, ${source.preserve.size} preserved` : ""),
  );
  return { changed: changed + removals.length, head, files: planned.size };
}

function main() {
  const { sources } = load();
  const heads = JSON.parse(fs.readFileSync(path.join(CACHE, "heads.json"), "utf8"));
  const wanted = sources.filter((s) => s.ownership === "mirrored" && (!only.size || only.has(s.name)));

  console.log(checkOnly ? "Checking mirror (no writes)" : "Mirroring");

  const lock = readLock();
  let totalChanged = 0;
  for (const source of wanted) {
    const head = heads[source.name];
    if (!head) {
      console.log(`  ${source.name}: not fetched, skipping`);
      continue;
    }
    const result = mirrorOne(source, head);
    totalChanged += result.changed;
    lock[source.name] = {
      repo: source.repo,
      ref: source.ref,
      commit: head,
      sourcePath: source.sourcePath,
      targetPath: source.targetPath,
      files: result.files,
      mirroredAt: new Date().toISOString(),
    };
  }

  if (!checkOnly) writeLock(lock);

  if (checkOnly && totalChanged > 0) {
    console.log(`\n${totalChanged} change(s) pending.`);
    process.exit(1);
  }
  console.log(totalChanged ? `\n${totalChanged} change(s) written.` : "\nUp to date.");
}

if (require.main === module) main();
module.exports = { mirrorOne };
